services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: lms
      POSTGRES_PASSWORD: lms
      POSTGRES_DB: lms_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://lms:lms@db:5432/lms_dev
      JWT_SECRET: secret-key
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

volumes:
  postgres_data:
  bundle_cache:
